apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .namespace }}
  name: {{ .name }}
data:
  APP_NAME: "{{ .name }}"
  APP_ENV: "{{ .namespace }}"
  APP_DEBUG: "true"

  GIT_HOST: "{{ .git_host }}"
  GIT_NAMESPACE: "{{ .git_namespace }}"

  APP_URL: "http://localhost"
  LOG_CHANNEL: "stack"

  DB_CONNECTION: "mysql"
  DB_HOST: "mysql"
  DB_PORT: "3306"

  BROADCAST_DRIVER: "log"
  CACHE_DRIVER: "file"
  CACHE_PREFIX: "{{ .name }}"
  SESSION_DRIVER: "file"
  SESSION_LIFETIME: "10080"
  QUEUE_DRIVER: "sync"

  REDIS_HOST: "redis"
  REDIT_PASSWORD: "null"
  REDIS_PORT: "6379"

  DB_DATABASE: "{{ .name }}"
  DB_USERNAME: "{{ .name }}"

