apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .namespace }}
  name: {{ .name }}-{{ .version }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ .storageClass }}
