apiVersion: v1
kind: Service
metadata:
  namespace: production
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: {{ .name }}
