# ------------------------------------------------------------------------------------------------------------
# Application namespace.
# ------------------------------------------------------------------------------------------------------------
namespace: {{ .namespace }}

# ------------------------------------------------------------------------------------------------------------
# Name of the application.
# This will be use mostly in every resource of the release to identify.
# ------------------------------------------------------------------------------------------------------------
name: {{ .name }}

# ------------------------------------------------------------------------------------------------------------
# Version of the application.
# Note: "v" will be always be prefix to avoid unexpected error while deploying artifact.
# ------------------------------------------------------------------------------------------------------------
version: {{ .version }}

# ------------------------------------------------------------------------------------------------------------
# Storage class may vary depending on your application
# Please make sure storage class exists inside the kubernetes cluster before you deploy any release.
# Neptune does not ship any storage class due to it may varies depending upon your kubernetes cluster.
# ------------------------------------------------------------------------------------------------------------
storageClass: default

# ------------------------------------------------------------------------------------------------------------
# Git
# If you want to download a private repository you can specify username and token inside git_host
# example: https://{username}:{token}@github.com
# ------------------------------------------------------------------------------------------------------------
git_host: "github.com"

# ------------------------------------------------------------------------------------------------------------
# Neptune will automatically generate the full URL while building artifact.
# Please checkout {{ .name }}/artifact.yml
# ------------------------------------------------------------------------------------------------------------
git_namespace: "lumenite"
